config {
  type: "view",
  schema: "staging",
  assertions: {
    uniqueKey: ["product_category_name_portuguese"],
    nonNull: ["product_category_name_portuguese"]
  }
}

with source as (
    select * from ${ref("product_category_name_translation")}
),

renamed as (
    select
        product_category_name as product_category_name_portuguese,
        product_category_name_english

    from source
)

select * from renamed