config {
  type: "view",
  schema: "staging",
  description: "Cleaned version of customer table"
}

with source as (
    select * from ${ref("olist_order_items_dataset")}
),

renamed as (
    select
        order_id,
        order_item_id,
        product_id,
        seller_id,
        
        timestamp(shipping_limit_date) as shipping_limit_date,
        
        price,
        freight_value,

    from source
)

select * from renamed