config {
  type: "view",
  schema: "staging",
  description: "Cleaned version of customer table"
}

with source as (
    select * from ${ref("olist_geolocation_dataset")}
),

renamed as (
    select
        geolocation_lat as latitutde,
        geolocation_lng as longtitude,
        geolocation_city as city,
        geolocation_state as state,
        geolocation_zip_code_prefix as zip_code_prefix

    from source
)

select * from renamed