config {
  type: "view",
  schema: "staging",
  assertions: {
    uniqueKey: ["unique_id"],
    nonNull: ["order_id"]
  }
}

with source as (
    select * from ${ref("olist_order_payments_dataset")}
),

renamed as (
    select
        ${surrogate_key.surrogate_key(
            ["order_id","payment_sequential"]
        )} as unique_id,
        order_id,
        payment_sequential,
        payment_type,
        payment_installments,
        payment_value,

    from source
)

select * from renamed