config {
  type: "view",
  schema: "staging",
  assertions: {
    uniqueKey: ["unique_id"],
    nonNull: ["order_id"]
  }
}

with source as (
    select * from ${ref("olist_order_payments_dataset")}
),

renamed as (
    select
        md5(cast(concat(order_id, payment_sequential) as string)) as unique_id,
        order_id,
        payment_sequential,
        payment_type,
        payment_installments,
        payment_value,

    from source
)

select * from renamed