name: pr_to_master

on:
  pull_request:
    branches:
      - master

jobs:
    pr_to_master:
      name: pr_to_master
      runs-on: ubuntu-latest
  
      steps:
        - name: Check out
          uses: actions/checkout@master
  
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - run: npm ci
        - run: npm test

        - name: Install dependencies
          run: npm i -g @dataform/cli
  
        - name: Dataform check
          run: dataform run